name: "Nightly Build"

on:
  schedule:
  - cron: "1 2 * * *"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this Repository
        uses: actions/checkout@v3
      - name: Checkout s3s Repository
        uses: actions/checkout@v3
        with:
            repository: "frozenpandaman/s3s"
            path: "s3s"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Get S3S latest commit
        run: |
          echo S3S_COMMIT=$(cd s3s && git rev-parse --short HEAD) >> $GITHUB_ENV
      - name: Read Docker Image Identifiers
        run: |
          echo REPO_OWNER=$(echo ${{ env.GITHUB_REPOSITORY_OWNER }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Configure Github Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/s3s:latest-${{ steps.date.outputs.date }}
            ghcr.io/${{ env.REPO_OWNER }}/s3s:latest
            ghcr.io/${{ env.REPO_OWNER }}/s3s:commit-${{ env.S3S_COMMIT }}
            docker.io/${{ env.REPO_OWNER }}/s3s:latest-${{ steps.date.outputs.date }}
            docker.io/${{ env.REPO_OWNER }}/s3s:latest
            docker.io/${{ env.REPO_OWNER }}/s3s:commit-${{ env.S3S_COMMIT }}
        env:
            S3S_COMMIT: ${{ env.S3S_COMMIT }}
